### ISSUE TITLE
'isWithinRange' is not exported from 'date-fns'.

### ISSUE THREAD

**Issue by therealnemethmate** [jonas-arkulpa/material-date-range-picker#12]
After importing it, I get the following error:

**_Failed to compile
./node_modules/material-date-range-picker/dist/material-ui-pickers.esm.js
Attempted import error: 'isWithinRange' is not exported from 'date-fns'._**

[date-fns changelog](https://github.com/date-fns/date-fns/blob/master/CHANGELOG.md
)
BREAKING: functions renamed:
areRangesOverlapping → areIntervalsOverlapping
eachDay → eachDayOfInterval
getOverlappingDaysInRanges → getOverlappingDaysInIntervals
isWithinRange → isWithinInterval

This could be the problem?

**Comment by adoel90** [comment]
i fixed this problem with upgrade "date-fns" in package.json inside "/node_modules/material-date-range-picker" to version :  "date-fns": "^2.0.0-beta.4"

**Comment by jonas-app** [comment]
Sry for the late response.
This lib was build for date-fns version 1 (^1.29.0).
Until now I never tested it with the newest version.
I do not plan to test beta builds.

@adoel90 If all things work and the stable version 2 is released I would welcome a PR. 😃 

Also the base lib works requires version 1 atm.
https://github.com/geeofree/kalendaryo/blob/master/package.json#L42
