### ISSUE TITLE
Remove Focus

### ISSUE THREAD

**Issue by dreamsparkx** [jonas-arkulpa/material-date-range-picker#7]
Is there any way to remove focus from the component if the from and to date are selected. Even after selecting it keeps the date picker window opened.

**Comment by jonas-app** [comment]
@dreamsparkx Yes that should be possible.
Downshift provides a `closeMenu` function which could be called at any point of the `setDateRange` function.
https://github.com/jonas-arkulpa/material-date-range-picker/blob/88cfbbc1bcc59df1aa21840daea027f3420b583e/lib/src/DateRangePicker.js#L41
The biggest question is: How to provide the most flexible API here.
Maybe I find some time the coming weeks to implement this suggestion.
I would also welcome a PR or any additional feedback regarding your opinion about a prop API.

**Comment by dreamsparkx** [comment]
@jonas-arkulpa Ok, I will try to add this coming Sunday.
